//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinderForWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoProj
    {
        public int IDProyecto { get; set; }
        public decimal Pago { get; set; }
    
        public virtual ProyectoInfo ProyectoInfo { get; set; }
    }
}
