//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinderForWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoInfo()
        {
            this.HabilidadesReqProyectoes = new HashSet<HabilidadesReqProyecto>();
            this.Matches = new HashSet<Match>();
            this.UsuarioInfoes = new HashSet<UsuarioInfo>();
        }
    
        public int ProyectoID { get; set; }
        public int HorasTrabajo { get; set; }
        public string NombreProyecto { get; set; }
        public string Descripcion { get; set; }
        public string Campo { get; set; }
        public string Matricula { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesReqProyecto> HabilidadesReqProyectoes { get; set; }
        public virtual HorasServicioDada HorasServicioDada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
        public virtual PagoProj PagoProj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioInfo> UsuarioInfoes { get; set; }
    }
}
