//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinderForWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasUsuario
    {
        public string Matricula { get; set; }
        public string Tarjeta { get; set; }
    
        public virtual UsuarioInfo UsuarioInfo { get; set; }
    }
}
