//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TinderForWork.Classes;

namespace TinderForWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioInfo()
        {
            this.HabilidadesUsuarios = new HashSet<HabilidadesUsuario>();
            this.HabilidadesUsuarios1 = new HashSet<HabilidadesUsuario>();
            this.Matches = new HashSet<Match>();
            this.TarjetasUsuario = new HashSet<TarjetasUsuario>();
            this.ProyectoInfoes = new HashSet<ProyectoInfo>();
        }
    
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Contrasena { get; set; }
        public string Correo { get; set; }
        public int Carrera { get; set; }
        public string Campus { get; set; }
        public bool StatusOcupado { get; set; }
        public string Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesUsuario> HabilidadesUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesUsuario> HabilidadesUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetasUsuario> TarjetasUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoInfo> ProyectoInfoes { get; set; }
    }
}
